typo

diff --git a/assets/service/sysv b/assets/service/sysv
--- a/assets/service/sysv
+++ b/assets/service/sysv
@@ -43,7 +43,7 @@ start() {
     <% if ('daemon.configDir' in locals) { %>[ -e $config ] || exit 6<% } %>
     echo -n $"Starting $prog: "
     
-    su - $user -c "NODE_ENV=production $exec $config >/dev/null 2>&1 & echo \$! > $pidfile" &&  echo_success || echo_failure
+    su - $user -c "NODE_ENV=production $exec $config >/dev/null 2>&1 & echo \$! > $pidfile" && echo_success || echo_failure
     
     retval=$?
     echo
