systemd works

diff --git a/assets/service/sysv b/assets/service/sysv
--- a/assets/service/sysv
+++ b/assets/service/sysv
@@ -23,14 +23,15 @@
 . /etc/init.d/functions
 
 exec="<%= daemon.systemTarget %>"
-prog="<%= name %>"
-<% if ('daemonConfigDir' in locals) { %>
+prog="<%= daemon.name %>"
+<% if ('configDir' in locals.daemon) { %>
 config="<%= daemon.configDir %>"
 <% } %>
-<% if ('user' in locals) { %>
-user="<%= user %>"
-<% } else { %>
-user="root"
+<% if (locals.daemon.user) { %>
+user="<%= daemon.user %>"<% } else { %>user="root"
+<% } %>
+<% if (locals.daemon.group) { %>
+group="<%= daemon.group %>"<% } else { %>group="root"
 <% } %>
 
 [ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog
@@ -45,7 +46,7 @@ start() {
     <% if ('daemon.configDir' in locals) { %>[ -e $config ] || exit 6<% } %>
     echo -n $"Starting $prog: "
     
-    su - $user -c "NODE_ENV=production $exec $config >/dev/null 2>&1 & echo \$! > $pidfile" &&  echo_success || echo_failure
+    su - $user -g $group -c "NODE_ENV=production $exec $config >/dev/null 2>&1 & echo \$! > $pidfile" &&  echo_success || echo_failure
     
     retval=$?
     echo
